version: '3.8'

services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5111 manage:app
    volumes:
      - static_volume:/home/app/web/project/static
      - media_volume:/home/app/web/project/media
    expose:
      - 5111
    env_file:
      - ./.env.prod
    depends_on:
      - postgres
  postgres:
    build: ./services/postgres
    volumes:
      - ./:/tmp/db
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    ports:
      - 5112:5432
  nginx:
    build: ./services/nginx
    volumes:
      - static_volume:/home/app/web/project/static
      - media_volume:/home/app/web/project/media
    ports:
      - 5111:80
    depends_on:
      - web

volumes:
  postgres_data_prod:
  static_volume:
  media_volume:
